### ISSUE TITLE
Update media links

### ISSUE THREAD

**Issue by lognaturel** [UDub-Impact/OData-Connector#14]
There's currently no way to auth media links so they'll just fail. Central v1.2 will introduce a frontend route to download media. https://github.com/getodk/central-frontend/pull/413

Links have the same structure as the API, but replace /v1 with /#/dl. Examples:
* https://test.getodk.cloud/#/dl/projects/149/forms/all-widgets.xml 
* https://test.getodk.cloud/#/dl/projects/149/forms/all-widgets/Submissions/uuid%3A104de350-f2c9-4077-9c92-003eff70aa8d/attachments/1539783149075.jpg

**Comment by lognaturel** [comment]
Central v1.2 is now out and the sandbox has been updated. Docs for this feature are at https://docs.getodk.org/central-submissions/#setting-up-media-downloads

**Comment by samlevy3** [comment]
We just submitted a pull request fixing this issue!
