### ISSUE TITLE
Use ODK logo

### ISSUE THREAD

**Issue by lognaturel** [UDub-Impact/OData-Connector#15]
I think it's important for users to see the ODK logo in the connector gallery. That's what will give them confidence that they've found the right connector. If that sounds ok to you, please add the following image to the repo and update the manifest:

![logo](https://user-images.githubusercontent.com/967540/117068749-87725180-ace0-11eb-8137-b9848d7088e7.jpg)

**Comment by wenjunsun** [comment]
yep, sounds good to me! Also I noted that the google appscript manifest already has the ODK logo, so that is great!
