### ISSUE TITLE
If there's only a Submission table, default to that and immediately show row filters

### ISSUE THREAD

**Issue by lognaturel** [UDub-Impact/OData-Connector#18]
If this is possible, it would be nice to save some clicks.

**Comment by wenjunsun** [comment]
In my knowledge, Google doesn't provide a method for defaulting to an option in a select menu. So one option would be, when there is only one table, we display a textbook that says the table you picked is "Submissions".

I don't know if this is ideal as it is unexpected for the user as they see the select bar sometimes and doesn't see it the other times. Anyways, I think reworking this would be a lot of hassle? If this isn't a priority, I would lean toward not changing things right now.

**Comment by wenjunsun** [comment]
@lognaturel As discussed this morning, I think it is fine to just drop the dropdown menu of the tables to pick all together if there is only one table (i.e. Submissions). I just implemented this fix. (change also is manifested in the appscript project) Can you please test it and see if everything behaves as they should? (for both one table case and multiple tables case)

Also, in my code I made a little assumption that if there is only one table, that table's name must be **Submissions**. Is this likely to stay true in the future?

Once you give the green light, I can create a new appscript production out of the newer version of code!

Thanks!

**Comment by lognaturel** [comment]
Looks perfect, thank you! Yes, if there's only one table, it will always be named `Submissions`.

Please publish and be sure to pick up the latest manifest changes I just pushed.

**Comment by wenjunsun** [comment]
Just published it with both changes!
