### ISSUE TITLE
Latitude and longitude are flipped for locations

### ISSUE THREAD

**Issue by lognaturel** [UDub-Impact/OData-Connector#2]
I am able to successfully create a map of points in the explorer by selecting the "bubble map" chart type and then dragging a geopoint field into the Fields/Location area of Data.

The OData field provides points as GeoJSON:

```json
{
"type":"Point",
"coordinates":[-4.535363674163818,9.869207382202148,0],
"properties":{
  "accuracy":1
  }
}
```

The first two coordinates are longitude and latitude, in that order. Google Data studio points are represented as latitude, longitude. For the point above, I would expect to see `9.869207382202148, -4.535363674163818` in GDS and I would expect it to be mapped in Burkina Faso.

**Comment by wenjunsun** [comment]
Thank you Helen for point this out! This has been fixed, and indeed this is why we only plotted one single point when there are many data points in the dataset, simply because some points are literally not on the map when latitude and longitude are flipped.

**Comment by lognaturel** [comment]
> some points are literally not on the map when latitude and longitude are flipped

Oh, that makes sense! Glad that was the fix.
