### ISSUE TITLE
Add documentation about published connector

### ISSUE THREAD

**Issue by lognaturel** [UDub-Impact/OData-Connector#22]
- [x] Update docs to reflect that connector is published

in Readme:
- [x]  Document that Google Cloud Platform project is at https://console.cloud.google.com/home/dashboard?project=getodk-gds
- [x] Document that deployed script project is at https://script.google.com/home/projects/1wqcrVE9bDDIpmldgHWpQCtnB9isz_aWxhbSM_udaTgFR02vp2z079B-S
- [ ] Document that ln@getodk.org, email@getodk.org have access to all accounts

**Comment by wenjunsun** [comment]
Hello @lognaturel , when I was trying to go to the Google Cloud Platform project link, it says that I don't have permissions to view it. Just want to know if that is expected?
![image](https://user-images.githubusercontent.com/18237212/121983241-da124500-cd45-11eb-857f-92aaf2367855.png)

**Comment by lognaturel** [comment]
> when I was trying to go to the Google Cloud Platform project link, it says that I don't have permissions to view it. Just want to know if that is expected?

Yes, that's expected because it's an ODK resource. The idea is to document the link in case I forget/get hit by a bus so it's possible to get access.

> what do you mean by ln@getodk.org, email@getodk.org having access to all accounts?

Maybe more "are on all projects"? I mean that they have access to the Google Cloud Platform account and the script project. email@getodk.org is the official contact address for the connector. Again, the idea is to have this info available so it's always possible to connect the dots no matter what happens to me as an individual. You might want to also document some of the access/ownership you've set up (e.g. your gmail is the owner of the scripts project).

**Comment by wenjunsun** [comment]
Hello @lognaturel, I just updated the README and the guide as requested. Let me know if the change looks good. I am going to close this issue, but feel free to reopen it if there are still some documentation changes that I need to make!
