### ISSUE TITLE
OData version

### ISSUE THREAD

**Issue by monty241** [UDub-Impact/OData-Connector#25]
I am curious about what OData version is supported, 3 or 4?

**Comment by lognaturel** [comment]
This connector isn't a generic OData connector but specifically for [ODK Central](https://docs.getodk.org/central-intro/) which implements the [4.0 Minimal Conformance level](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part1-protocol/odata-v4.01-cs01-part1-protocol.html#_Toc505771292). You can read more about what Central supports [here](https://odkcentral.docs.apiary.io/#reference/odata-endpoints).

**Comment by monty241** [comment]
Thank you! It was worth a try. The current logic can't pass `/sessions`.

Background for the question was that we have a generic OData4 producer on https://cloud.invantive.com (actually the data is coming from https://bridge-online.cloud/NAME/odata4/...) and a limited audience prefers to use Google Data Studio instead of Power BI / Query / Azure Data Factory.

Google Data Studio is a too small audience to justify investing in a generic OData connector ourselves; chicken and the egg problem.
