### ISSUE TITLE
Repeats issue

### ISSUE THREAD

**Issue by lognaturel** [UDub-Impact/OData-Connector#26]
https://forum.getodk.org/t/repeats-with-google-data-studio-connector/33891/5, form is at https://sandbox.getodk.cloud/#/projects/4/forms/devliveplus2020/ (credentials needed)

**Comment by samlevy3** [comment]
Adding a further description to this issue. Currently, the code does not handle nested repeats. We need to add functionality to ensure that nested repeats and groups are handled correctly by creating a separate table for each repeat. Close to closing this issue, made changes, and doing further testing. So far appears to be working though.
