### ISSUE TITLE
Guide update suggestions

### ISSUE THREAD

**Issue by lognaturel** [UDub-Impact/OData-Connector#3]
> Go to project settings → show appsscript.json → copy appscript.json

This is for the new IDE. For consistency, it would be helpful to get instructions for the old IDE.

> login to our connector here.

Instead, you should describe how to launch from the new project the user has created. It looks like https://datastudio.google.com/u/0/datasources/create?connectorId=AKfycbwlLqb1ZWaB0mPpdfG8o-JhKv6BnPubbqL-VLg9cfA is actually a copy of an npmjs-related project. A screenshot might be helpful here.

**Comment by wenjunsun** [comment]
Hello Helene, can you provide more specific details about how to update the guide? From what I am understanding you want us to write up the guide about how to deploy the connector using the old IDE? I am a little confused on "Instead, you should describe how to launch from the new project the user has created." Can you elaborate more? Thanks

**Comment by lognaturel** [comment]
In the [using the connector](https://github.com/UDub-Impact/OData-Connector/blob/master/connector%20guide.md#using-the-connector) section, there's a direct link to a connector in step 3. That's not right, instead it should describe how to find the URL for the copy that the user made following the "editing the connector" section.

**Comment by PieterBenjamin** [comment]
Updated using your feedback and Florians original. Was useful to step away from a while to see the issues with new eyes. We'll try to add some screenshots after submitting ODK Central as a source in case there's any more visual cues.

**Comment by lognaturel** [comment]
Great!

> or use the most recent version of ours here

This still is a copy of an npm project. I'd recommend not linking to a hosted version at the moment. There are some scary warnings about it not being trusted and I think it's generally better if users have control over the code since it's a simple process.

The rest looks good.
