### ISSUE TITLE
Explore a way to expire URL and credentials cache

### ISSUE THREAD

**Issue by lognaturel** [UDub-Impact/OData-Connector#31]
It appears that currently the path, username and password provided on first configuration are cached forever. That doesn't seem like a good thing. At best it's a barrier to connecting to more than one server and causes problem if e.g. a user's password changes. At worse it's a security concern. What are alternatives?

**Comment by samlevy3** [comment]
Added logout feature in the referenced commit. Will also check to ensure the user is logged into the correct server when accessing forms and log the user out if logged into the wrong server.
