### ISSUE TITLE
For geopoint types, add column for accuracy

### ISSUE THREAD

**Issue by lognaturel** [UDub-Impact/OData-Connector#5]
Points from the OData feed are represented in GeoJSON:
```json
"geopoint_widget":{
  "type":"Point",
  "coordinates":[-4.535363674163818,9.869207382202148,0],
  "properties":{
    "accuracy":1
    }
  }
```

It would be helpful to introduce a column that has name `<field name>-accuracy` to provide the accuracy. For the example above, the column would be named `geopoint_widget-accuracy`.

**Comment by wenjunsun** [comment]
It has been taken care of now! 
![image](https://user-images.githubusercontent.com/18237212/105430366-2b3f6200-5c08-11eb-870e-6ff961d29044.png)

**Comment by lognaturel** [comment]
🎉 🎉
