### ISSUE TITLE
Google Verification Process

### ISSUE THREAD

**Issue by PieterBenjamin** [UDub-Impact/OData-Connector#6]
There are a few items to consider as we ramp up towards the Google [Partner Verification](https://developers.google.com/datastudio/connector/pscc-requirements). 

[Published connector](https://datastudio.google.com/u/0/datasources/create?connectorId=AKfycbz5hy64bfHz3b92xxIVm6oW59Qh6mBGGZ62x7sjmz8y4vfN4dPZjG27DhH1xmHrkbeAYw)

Impact++
- [x] Manifest should contain values for shortDescription, authType, feeType, privacyPolicyUrl, and termsOfServiceUrl
    - H proposed `shortDescription`: "Connect to your ODK Central server and build dashboards for all your projects."
- [x] If the user needs an account to use the connector, make sure the connector description or the addOnUrl link provides instructions to help the user create one.
    - H proposed `description`: "Explore and visualize your ODK data. To use this connector, you will need a Web User account on a Central server. If you don't already have a Central server, you can [set one up yourself](https://docs.getodk.org/central-install/)."
- [x] Provide meaningful and actionable error messages to users when users encounter a Connector internal error. This includes cases when a user provides invalid/blank input at configuration.
- [x] [Create a deployment](https://developers.google.com/datastudio/connector/deploy#create_separate_deployments) named Production and update the Production deployment to contain the version of code you want to publish.
- [x] [Share view access](https://support.google.com/drive/answer/2494822) of your Apps Script project with both of these addresses:
data-studio-contrib-qa@googlegroups.com, data-studio-contrib@google.com; give edit access to email@getodk.org, ln@getodk.org, it should run as email@getodk.org

@lognaturel/ODK
- [x] Publish page on getodk.org - https://getodk.org/gds
- [x] Verify [page ownership](https://support.google.com/webmasters/answer/9008080?ref_topic=7440006#zippy=)
- [x] Set hosted page as `addOnUrl`
- [x] Complete the [OAuth Client Verification](https://developers.google.com/apps-script/guides/client-verification) process. See [FAQ](https://support.google.com/cloud/answer/9110914). [add your connector's required OAuth scopes](https://developers.google.com/datastudio/connector/images/scopes-for-oauth-consent-screen.png)
  - [x] Set [Google Cloud Platform Project for script](https://developers.google.com/apps-script/guides/cloud-platform-projects#switching_to_a_different_standard_gcp_project)
  - [x] [Configure OAuth screen](https://developers.google.com/apps-script/guides/cloud-platform-projects#completing_the_oauth_consent_screen)
  - [x] Finalize #15, #16, re-publish, verify test app
  - [x] Add justification for sensitive scope:
    > This Google Data Studio connector's purpose is to let users analyze data from their own ODK Central server. In order to achieve this, the connector must be able to make queries to the server that the user configures. The connector only makes read requests and we additionally recommend providing read-only credentials to limit what the script could do. We have followed the instructions for building a Google Data Studio connector at https://developers.google.com/datastudio/connector/build.
  - [x] Create YouTube video describing how sensitive scopes will be used [here](https://www.youtube.com/watch?v=dw87M50pzTg)
  - [x] Submit OAuth screen for verification
- [x] Address #17, redeploy
- [x] Authorize and test your connector using a new account after passing the OAuth verification process to ensure that Unverified app screen is not displayed to your users.
- [x] Fill out [gallery application](https://docs.google.com/forms/d/e/1FAIpQLSd8ozb3FnBrDC4tgzUKgTf_dyho-479Z7fcGkV3PQrePQCSMA/viewform)
  > Screencast from OAuth authorization shows all except deployment id: https://www.youtube.com/watch?v=dw87M50pzTg

  > Path: https://sandbox.getodk.cloud/v1/projects/8/forms/range.svc
  > username: ln+gdsverification@getodk.org
  > password: t4-PgaDAsqfTqcybJkHZWNMTm7qEMu

  > When configuring, you will need to enter https://sandbox.getodk.cloud/v1/projects/8/forms/range.svc again, then Submissions and then can connect

  > (Note, the configuration URL is required because you could connect to several different forms on the same server. For example, you can configure a separate dataset from https://sandbox.getodk.cloud/v1/projects/8/forms/Geotrace%20and%20shape.svc)

TODO after
- [x] Document that Google Cloud Platform project is at https://console.cloud.google.com/home/dashboard?project=getodk-gds
- [x] Document that deployed script project is at https://script.google.com/home/projects/1wqcrVE9bDDIpmldgHWpQCtnB9isz_aWxhbSM_udaTgFR02vp2z079B-S
- [x] Document that ln@getodk.org, email@getodk.org have access to all accounts

**Comment by lognaturel** [comment]
Gallery application submitted May 10. The confirmation screen says we should expect an answer in 2-3 weeks.

**Comment by wenjunsun** [comment]
TODO for google feedback:
- [ ] create template?? Can't do it because schema isn't fixed
- [ ] change name of connector so we don't have the word "connector" in it.
- [ ] stop using shorthand names for Data Studio in the manifest or "learn more page"
- [ ] support URL should allow user to report an issue or get support.
- [ ] screen cast and credentials?

**Comment by lognaturel** [comment]
Thanks, all! I have just resubmitted.

**Comment by lognaturel** [comment]
Latest rejection:

- supportUrl should be a hosted page where users can go to get support for your connector. This cannot be an email or mailto link.
The `supportUrl` link you provided does not provide a way for users to report an issue or get support.
- The test credentials provided are invalid or not working. Please provide valid test credentials for the connector.

For 1, could someone please look at other connectors and what they provide as their support link? Maybe https://github.com/UDub-Impact/OData-Connector/issues/new with an issue template would work? I’m starting to wonder whether “hosted” means “hosted on getodk.org”? Although forum.getodk.org seems it would meet that. 

Not sure what’s going on with 2. I tried the credentials with a fresh Google account right before submitting.

**Comment by wenjunsun** [comment]
I looked at other connectors' support URL, and majority of them just points to their GitHub issues page, so that is what I did as well.

In terms of the credentials, are there details about why it doesn't work? I don't know what I can do to help?

**Comment by lognaturel** [comment]
We looked at other connectors in the [gallery](https://datastudio.google.com/data) and saw mostly support forms available on or linked from the organization's page. Based on that, I introduced https://getodk.org/google-data-studio/#help

I do see a 500 in the sandbox logs. The only thing I can think of is that it happened around the time when the server was upgraded to Central v1.2. We may just have gotten really unlucky and had the verifiers check in the 2-3 mins of downtime around that. I can't reproduce no matter what I try so have resubmitted exactly the same credentials.

**Comment by lognaturel** [comment]
![72A150BA-F177-432B-A3F0-125C33F89E3F](https://user-images.githubusercontent.com/967540/121842435-44b77800-cc95-11eb-9b86-ade814b71cdd.jpeg)

Thanks and congrats, everyone!

**Comment by lognaturel** [comment]
Thanks @samlevy3, that indeed was the issue. I'm puzzled because I did a bunch of testing with different Central servers at some point and my recollection was that when I revoked the connector's access through my Google privacy settings I could then go through the full process again. Either there's something else I was doing that I can't remember or the behavior has changed. Either way, there are some improvements that could be made and I'll file a few issues. I've confirmed that the instructions I provided previously do work with a fresh connection.

**Comment by lognaturel** [comment]
Resubmitted Nov 15

**Comment by lognaturel** [comment]
Dec 29, received rejection:

>     Please add `urlFetchWhitelist` to your connector's manifest. See manifest reference for more details: https://developers.google.com/datastudio/connector/manifest

I responded quoting the docs which say "A list of HTTPS URL prefixes which your connector uses. Any URL endpoint fetched must match one of the prefixes in this list." and our application which says "ODK Central is an open source system that organizations self-host. We have no knowledge of where it is hosted." 

No response. Resubmitted again Jan 13.

**Comment by samlevy3** [comment]
The connector has been republished with updates and can be found live on the GDS connector gallery: https://datastudio.google.com/data?search=ODK

**Comment by lognaturel** [comment]
🤩🤩🤩
