### ISSUE TITLE
Simplify configuration process

### ISSUE THREAD

**Issue by lognaturel** [UDub-Impact/OData-Connector#7]
Here's a concept:
- From the auth screen, ask for an OData URL for a specific form.
- Extract the domain and built an auth URL from that
- On the next config screen, also prompt for OData URL and pre-populate it with the one that was supplied on the auth screen. That way a user can either keep it or if they want to access another form on the same server, put in a different form's OData URL.
- If possible, use the OData URL to populate a dropdown of tables instead of making that field an open text field. `Submissions` should always be the first option. This would require being able to react to the user making changes to the OData URL field while on that second config page and being able to update the dropdown contents. If it's not possible, the open text field is fine. Maybe the help text can say "e.g. Submissions or the name of a repeat"

As @PieterBenjamin described, I've confirmed it's not practical to change fields from the auth screen once they've been entered.

**Comment by wenjunsun** [comment]
Hello @lognaturel, I am trying to follow up on this issue. One thing that is hard for me is that I don't know what kind of URL users can enter and what form it can take on and how to parse that. Can you give some examples? Will it always look like https://sandbox.central.getodk.org/#/projects/124/forms/single-repeat? I don't have a ODK database so I don't know their interface. I've only interacted with the sandbox and maybe user's experience with their database is different from the sandbox? I would appreciate any further pointers.

**Comment by lognaturel** [comment]
Here's the reference: https://odkcentral.docs.apiary.io/#reference/odata-endpoints/odata-form-service/service-document

`v1/projects/projectId/forms/xmlFormId.svc` is what the URL that users copy from "analyze with Odata" would always end with.

**Comment by lognaturel** [comment]
To be explicit, you suggested `#/projects/projectId/forms/xlmFormId` (e.g. sandbox.central.getodk.org/#/projects/124/forms/single-repeat) which is a frontend URL. That would be fine too but I think it's good to get users always going to the same place to connect to an analysis tool. That's why I suggest instead using the OData service document. We can add a paragraph about your connector at the bottom of https://docs.getodk.org/central-submissions/#connecting-to-submission-data-over-odata and the interaction will be consistent with other analysis tools.

**Comment by wenjunsun** [comment]
@lognaturel Hello Helen, I just finished making the configuration process more intuitive. Can you please try out and see if it is behaving the way you expect? Thanks! Now it works with repeats too. At the second screen after you entered the URL select "Next" and you will see a dropdown menu containing all the tables user can access. 
One thing that I hope I can do but I can't accomplish is we can't populate the textbox in the second screen. So user has to enter the same URL twice, once in the first screen and once in the second screen. Hope that will not be too much to ask of user?
If you are satisfied we can close this issue. Thanks!

**Comment by wenjunsun** [comment]
Configuration process has been fixed!
