### ISSUE TITLE
Explore naming data source

### ISSUE THREAD

**Issue by lognaturel** [UDub-Impact/OData-Connector#9]
When I look at a list of data sources configured in my Google account, I see `ODK central API connector` over and over again. It would be great to use the form name in that source name. For example: `ODK Central - My Cool Form`. You should be able to fetch the form name using https://odkcentral.docs.apiary.io/#reference/forms-and-submissions/'-individual-form/getting-form-details and getting the `name` property.

**Comment by wenjunsun** [comment]
Hello Helen, as far as I can tell, there is no way to configure the name of the data source in our javascript code. However, it is very simple to do so in the user interface. I already included a guide of how to do this [here](https://github.com/UDub-Impact/OData-Connector/blob/master/connector%20guide.md#how-to-rename-your-data-source). Hope that this is acceptable.
